packages:
  - ember-provide-consume-context
  - test-app
  - test-app-ember-7
nodeLinker: hoisted
strictPeerDependencies: false
overrides:
  '@glimmer/manager': ^0.84.3
  '@glimmer/reference': ^0.84.3
  '@glimmer/validator': ^0.84.3
  form-data: 3.0.4
  handlebars: 4.7.9
syncInjectedDepsAfterScripts:
  - build
allowBuilds:
  core-js: true
